### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by adlerweb** [ricki-z/SDS011#11]
Readme states the serial pins have to be defined in the object and begin wouldn't accept any arguments. This has been changed in 45789614c5a0679f7656a8b166d9a6f42b0595ab. Readme should be updated accordingly.

**Comment by ricki-z** [comment]
@adlerweb Readme is updated. Can this issue be closed?

**Comment by adlerweb** [comment]
Well, looks updated to me…
(ref 9bfa85fcb77fd2b6bc2f113db3e2a01ecc11b81f)
